import { ROUTES } from "~/shared/constants/routes";

export const publicRoutes = [ROUTES.LANDING, ROUTES.LOGIN, ROUTES.CONFIRM, ROUTES.SIGNUP, ROUTES.FORGOT_PASSWORD, ROUTES.RESET_PASSWORD, ROUTES.TERMS_OF_SERVICE, ROUTES.PRIVACY_POLICY] as const
